apiVersion: v1
kind: Pod
metadata:
  name: exhibition-emojihunt
  namespace : democenter
  labels:
    app : exhibition-emojihunt
spec:
  containers:
  - name: exhibition-emojihunt
    image: registry.cn-hangzhou.aliyuncs.com/blackwalnutlab-democenter/exhibition-emojihunt:v1.1
    livenessProbe:
      httpGet:
        path: /
        port: 8080
        httpHeaders:
          - name: X-Custom-Header
            value: Awesome
      initialDelaySeconds: 10
      periodSeconds: 10
---
kind: Service
apiVersion: v1
metadata:
  name: exhibition-emojihunt-nodeport
  namespace: "democenter"
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 31500
  selector:
    app: exhibition-emojihunt